
# vim:ft=kitty

# =========================
# Colores base
# =========================
foreground              #dcdcdc
background              #282828
selection_foreground    #282828
selection_background    #dcdcdc

# =========================
# Cursor
# =========================
cursor                  #dcdcdc
cursor_text_color       #282828

# =========================
# URL hover
url_color               #dcdcdc

# =========================
# Kitty window border
active_border_color     #dcdcdc
inactive_border_color   #737994
bell_border_color       #FFE000

# =========================
# Tab bar
active_tab_foreground   #282828
active_tab_background   #dcdcdc
inactive_tab_foreground #dcdcdc
inactive_tab_background #383838
tab_bar_background      #282828

# =========================
# Marks
mark1_foreground #282828
mark1_background #dcdcdc
mark2_foreground #282828
mark2_background #C83545
mark3_foreground #282828
mark3_background #0099d7

# =========================
# Los 16 colores del terminal
# Normal colors
color0  #000000
color1  #C83545
color2  #00cf1c
color3  #FFE000
color4  #0099d7
color5  #F5C2E7
color6  #00aac2
color7  #dcdcdc

# Bright colors
color8  #000000
color9  #e83535
color10 #61ff54
color11 #FFE000
color12 #0099d7
color13 #FF00FF
color14 #00ffe0
color15 #dcdcdc
