general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.disp.dpms({ action = "enable" })'
}

# listener {
#   timeout = 5
#   on-timeout = notify-send "Bye"
#   on-resume = notify-send "Hola"
# }

listener {
  timeout = 180
  on-timeout = brightnessctl -s set 20
  on-resume = brightnessctl -r
}

listener {
    timeout = 300 # 5 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 400
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

listener {
    timeout = 800                                # 
    on-timeout = systemctl suspend                # suspend pc
}

###sdbus-cpp
